# Generated by Django 4.2 on 2023-04-21 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcAPI', '0002_alter_inmueble_construction_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='created',
        ),
    ]
